### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by gebaltso** [idonahum/photoVerse#25]
Hello! When I try to run `./generate_container_exec.sh` I get the following :

`=============
== PyTorch ==
=============

NVIDIA Release 24.01 (build 80741402)
PyTorch Version 2.2.0a0+81ea7a4

Container image Copyright (c) 2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

Copyright (c) 2014-2023 Facebook Inc.
Copyright (c) 2011-2014 Idiap Research Institute (Ronan Collobert)
Copyright (c) 2012-2014 Deepmind Technologies    (Koray Kavukcuoglu)
Copyright (c) 2011-2012 NEC Laboratories America (Koray Kavukcuoglu)
Copyright (c) 2011-2013 NYU                      (Clement Farabet)
Copyright (c) 2006-2010 NEC Laboratories America (Ronan Collobert, Leon Bottou, Iain Melvin, Jason Weston)
Copyright (c) 2006      Idiap Research Institute (Samy Bengio)
Copyright (c) 2001-2004 Idiap Research Institute (Ronan Collobert, Samy Bengio, Johnny Mariethoz)
Copyright (c) 2015      Google Inc.
Copyright (c) 2015      Yangqing Jia
Copyright (c) 2013-2016 The Caffe contributors
All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.
0it [00:00, ?it/s]
/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
tokenizer/tokenizer_config.json: 100%|███████████████████████████████████████████████████████| 806/806 [00:00<00:00, 5.49MB/s]
tokenizer/vocab.json: 100%|██████████████████████████████████████████████████████████████| 1.06M/1.06M [00:00<00:00, 3.70MB/s]
tokenizer/merges.txt: 100%|████████████████████████████████████████████████████████████████| 525k/525k [00:00<00:00, 1.26MB/s]
tokenizer/special_tokens_map.json: 100%|█████████████████████████████████████████████████████| 472/472 [00:00<00:00, 7.25MB/s]
text_encoder/config.json: 100%|██████████████████████████████████████████████████████████████| 617/617 [00:00<00:00, 8.99MB/s]
model.safetensors: 100%|███████████████████████████████████████████████████████████████████| 492M/492M [00:08<00:00, 56.8MB/s]
vae/config.json: 100%|███████████████████████████████████████████████████████████████████████| 547/547 [00:00<00:00, 7.08MB/s]
diffusion_pytorch_model.safetensors: 100%|█████████████████████████████████████████████████| 335M/335M [00:05<00:00, 63.9MB/s]
unet/config.json: 100%|██████████████████████████████████████████████████████████████████████| 743/743 [00:00<00:00, 8.98MB/s]
diffusion_pytorch_model.safetensors: 100%|███████████████████████████████████████████████| 3.44G/3.44G [00:51<00:00, 66.7MB/s]
config.json: 100%|███████████████████████████████████████████████████████████████████████| 4.52k/4.52k [00:00<00:00, 38.2MB/s]
model.safetensors: 100%|█████████████████████████████████████████████████████████████████| 1.71G/1.71G [00:24<00:00, 68.7MB/s]
scheduler/scheduler_config.json: 100%|███████████████████████████████████████████████████████| 308/308 [00:00<00:00, 4.14MB/s]
Traceback (most recent call last):
  File "/workspace/generate.py", line 70, in <module>
    tokenizer, text_encoder, vae, unet, image_encoder, image_adapter, text_adapter, scheduler, _ = load_models(
  File "/workspace/models/modeling_utils.py", line 92, in load_models
    image_adapter, text_adapter, unet, lora_config = load_photoverse_model(photoverse_path, image_adapter, text_adapter, unet)
  File "/workspace/models/modeling_utils.py", line 14, in load_photoverse_model
    state_dict = torch.load(path, map_location="cpu")
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 996, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 445, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 426, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'final3_photoverse_facenet_lora_rank128/photoverse_040000.pt'`

Should I download the .pt file from where? And put it in which folder?
Thanks in advance.

**Comment by Haimzis** [comment]
Hi @gebaltso ,
You can download the model weights from our drive (we've published a link in the instructions). Simply place the weights in the same path as mentioned in the bash script.

Link: https://drive.google.com/drive/mobile/folders/1TGTYuRbVDQJCWbG4LIayHz5N46Pea8HI?usp=sharing

**Comment by Haimzis** [comment]
Closing this issue as it seems to be handled successfully
